import type { Metadata } from "next";
import { Geist, Geist_Mono,Kanit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const kanit = Kanit({
  subsets:['thai'],
  weight:['400','500','600','700'],
  display:'swap'
})
export const metadata: Metadata = {
  title: "EGAT NEXT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kanit.className} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
